version: "0.2"
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 889982481835.dkr.ecr.eu-west-3.amazonaws.com
    build:
      commands:
        - docker build -t $ImageName -f ./Dockerfile .
        - docker images
    post_build:
      commands:
        - docker tag $ImageName:latest 889982481835.dkr.ecr.eu-west-3.amazonaws.com/$ImageName:latest
        - docker push 889982481835.dkr.ecr.eu-west-3.amazonaws.com/$ImageName:latest
        - echo "test"